// This file is automatically generated using github.com/mjibson/esc.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/admin.html": {
		local:   "../assets.min/admin.html",
		size:    0,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/wEAAP//AAAAAAAAAAA=
`,
	},

	"/css/flat.css": {
		local:   "../assets.min/css/flat.css",
		size:    581,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/3yP0U7rMAyGX2VH5wakJerWwiCT+i5OnXYRrR056dhU7d3RRoAVBnfJlz//Z2uCvUpg
Y937GibLgk6UAPoxmuKkPYUxqU54DHUMQNdAASLTcpa5nHXLMqiGKQn3PzsDkLuBbSIVxA8gx+XlgkCd
k4nH1Htypvjnh8CSgNIsbKBJfu+WM9ZyM8bJQvNynotQNdyzmP9luQG72WZ5hmv3iFCdrqSzzox+q8Tn
h7Jqv1ViVbYl5F113uQ9YlbhsIjce1zkvzmmLONRWz7UWvjVEKc703qJSTU73+P9NIB0nlTiYNZFOGwD
IHrqvkAWFB/DnB+ubG7lKvd006aJ1U7+dhYzYfFpO70FAAD//91SfZ5FAgAA
`,
	},

	"/css/pipeline.css": {
		local:   "../assets.min/css/pipeline.css",
		size:    1259,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/6RU4W6jPBB8lUifqv75jCANrc48jcFrsqrjteylIUX37iewe8k1bnXSiR+A7dnZmR3Q
+FZ59GDRwa6KrEaIC8PMQlkcnRzAMYTufEQGEb0aQDo6B+V/lpD5vmiM3qqLRLfuit7S8NoZciwivoNs
Ws/p9Qw4Hlm+1HV3UmFEJ3pippNsaj93Z9R8lM1z6+c7OvBlFk8RGcnJAFYxvkGuclgLHhPd9pz5wrbS
wql7F+g0zLLuegoagghK4xRlWz90A1kK8j9jTDdMIVKQnnBz5qpq3/q52zq5pbnzsqCkwtFRAL3k2mpi
KhyTPRgK8H9hRxmGsAzkGBzLx8csepWVxWRfWz/vIlnUV6NUH8lODB2Tl81LtcpIesegLqU+EpsFw7Kp
64evW12Su18dMhgiCzKCLx6+UWfVzbFE/jF7Rw5KpW8hyx+jrksDAD1CtQnKjWfXtqWrZ3mwayA3t8Rh
/zum+6vXOTj1br2acnoTZWopSfoAp0D+A+fKuCvK9CpG0Euvhtcx0OS0yMF++qFU+1yCGIW2CNH9oT20
JUiYnEM3FjCmf/ou/neANYCfvrBPeKsuEP7uh/UrAAD//8EK/7DrBAAA
`,
	},

	"/css/style.css": {
		local:   "../assets.min/css/style.css",
		size:    2764,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/5xWC26rOhPeClIVqZHiiDxITxwpOhv4F2HwGPzX2JaZNOEi9n5lwEmA9JzqFqmdfuN5
eMbz2QWWapUaXjcFyLxAuonjRdsBlnEudU7QWJrE9tauhVSqKaUmT2tPz3JqbqSS/0id09Q4Do6k5tb+
LoFL9u4Nr5JjQY/Hrb0tGy6/1taZ/0OGSlY482y+wAllrrSQnIM+lczlUpPUIJqSkqP/sbdTyHPAA9wn
QDf2FlVGSR69cc4HdMgjjrw2juK2neRyFsaVfr8IblSI7dbeZosL14xzi6dJxSGw9zFOaeotKpI1B2RS
VWdJtcF3KqSrkGSFVHwZIikQSH/ZW/s22FYhTxo/sLOSd3gT+82efAxSYa2AYG2BaqMhZNfBtMstQJlR
xtFXteuqNwp1XltWVcBXr8CINYOv3ZGx5DCxFEyqmWUPPix5uk/2ycTSXbSWOl+9RB+2It1NDK9M4txw
QO+GuWP1rONrZZgvauhG19bE3k4INyRMyVzTDDSCezYlXxKuZw8gS0lmNILGkQs/ZkXyAjpXlulR7xM/
kchSBRH6eT2jOyNvvsChzJgakigl5wr6JJgGRfzSoSNNyrLP3JmL5lRJDcyR3DEuQeM7msj5SVwN3Yri
u+QzWr0JIUZSvFhG2hAHFhhO4/V9/Fm8vsc+3iD9h3hD8/8UcJ9wyFfomK4sc6DxWY62yWLlT8xDSOLF
aMX0/4+wMAjL0yO6J0XoB9D/etb0G6D9H1KfmJYlQ2k0HTZB7kh0qKJ+G5HUQmqJ0P7+hFo4VkIVzdY3
8eKpAsSaSnaOPeH5An6j3Mb+yE1K6lkpM2UpsRFGI7n2PP0Rx6/P1mP96i/6GS+8PDvf+5vqZ2zx+mx8
73C2YMwha3tRinSH9ZxeEI1e92MZprNTddTsHacXqTgZCD3yiDLPBzMQ7Ha7PYUoG/+dujoLVkpV0/8Z
zTKzKo02lWUZ3O+Xjgoe100fO/4+csc+/hDRwl+vLxLZ7/c/MO/4qJO0C9U5HA7jvDpGHFVlQpEdeOov
lJ0fDC4rq1hNpfauSapM9vnjbEqoKpZDcy0kAunqRK2Dv9hDabFu5rzdUbyv0PCOODxubbHz3+hKf9Lu
9sdfPA1azzeXiibxYtjnL7/P4ZnTyX2BKLugeZr+ykodbf848H6Jn/GOhvyDhTqDDOE9XvbzPVPsDjGH
fNm2b8P9RVLmiPejwTWh+P5F0K6ZruQ6NYrPBr5XOeD3sRCH7BDw3AHooEk3gn8cB00NSpnrw0iI4ybE
URcIiuMhS0VIoGQ5aHwMoPjYCT7ospqFQF5s/w0AAP//7glvM8wKAAA=
`,
	},

	"/img/failed.svg": {
		local:   "../assets.min/img/failed.svg",
		size:    726,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/4yS34vcIBDH/xWZpdDCJmpiuGuJeSrcU58K926iRotrgrr5cX99sb0e2+1uOQRhxvl8
5zuDbVxGtJ2cjxxMSvMXjNd1Lde6nMKIK0IIjssIaLUyGQ6PFJBRdjSJQ0Wga531SoSnIKRVPiErOQhA
W8WBANorDpSQD9C1MU0zmrSOKv16ynExTG4KHA59379mplkMNu0cSgr4iqK3a/DfFro2qCGhsHGo79lG
2jrH4dA0TVa4BPL98MYxdpNTpJGMZXQWyVxlkeTwrX5AxLClIqZgL9c9/mvqHNzHg/iUmfGPstYaUFJb
KoQfTF7ZyUrpFCA9+VRocbJu5/BV/RDPZ/Rd+Hh8VkEKL45PyqtFHKPwsYgqWP3KRPuiOFAKXZuF89z0
c9kA2jnQ5m1SQvP5HV4svoauP1snW5zhWxLsTkXz+P4WWlhn/XhPgv1Tgceuzd+1+xkAAP//R7Dg19YC
AAA=
`,
	},

	"/img/passed.svg": {
		local:   "../assets.min/img/passed.svg",
		size:    724,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/5SSXasbIRCG/4pMKLSQXXU/ejhl3avCuepV4dy7q64W4y5q9iO/vpimIU2TQhGEGed5
553BJswDWg/WBQY6xukLxsuy5EuZj37ABSEEh3kAtBgRNYNXAkhLM+jIoCDQNtY4yf2b58JIF5ERDDig
tWBAAG0FA0rIB2ibEMcJjUoFGc9PKc760Y6ewa7ruktmnHhv4sYgp4DvKPq4Bv9poW287CPyK4PymW2k
jLUMdnVdJ4VbIN0vV64uH3JVf+488ahvU0gw+Fa+IKKruSA6q0736v+0c/T2445/SszwW1YpBSjKNWbc
9Tot62CEsBKQGl3MFD8YuzH4Kn/w9yP6zl3Yv0svuOP7N+nkzPeBu5AF6Y26MMGcJANKoW2ScJqYvuY1
oI0Bra8zEprOr/Bm5SW03dFY0eAEP5KonlR8Lv6nycRDMG54LlL9VYOHtkmftf0ZAAD//yNy3HPUAgAA
`,
	},

	"/img/running.svg": {
		local:   "../assets.min/img/running.svg",
		size:    724,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/5SS3arcIBCAX0VmKbSwiZqfHk6JuSqcq14Vzr2JGi2uCWr+9umL7bJst7uFEgjMON/n
zGATlgFtJ+sCAx3j9AXjdV3ztcxHP+CCEILDMgBajYiawSsBpKUZdGRQEGgba5zk/s1zYaSLyAgGHNBW
MCCA9oIBJeQDtE2I44RGpYKMv45SnPWjHT2DQ9d1l8w48d7EnUFOAd9R9HEN/rOFtvGyj8hvDMpnbSNl
rGVwqOs6GW6B9H+5cnX5kFNdmbiJR32bQoLBt/IFEV0tBdFZdb63/7Od2duPB/4pMcNVqxSgKLeYcdfr
tKyTEcJKQGp0MVP8ZOzO4Kv8wd9n9J27cHyXXnDHj2/SyYUfA3chC9IbdWGCOUsGlELbJHGamL7mNaCd
Aa2vMxKavt/hzcpLaLvZWNHgBD9SVE8qPhf/c4mfnTNueC6p/qrBQ9ukx9r+DAAA//8uS+XC1AIAAA==
`,
	},

	"/img/waiting.svg": {
		local:   "../assets.min/img/waiting.svg",
		size:    730,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/5SSXavbMAyG/4pRGWzQxHY+djgjztXgXO1q0HsntmMP1wm2m4/++uGtK13XDg6CgBQ9
r14JN2Ee0Hq0LjDQMU5fMF6WJV/KfPQDLgghOMwDoMWIqBm8EkBamkFHBgWBtrHGSe7fPBdGuoiMYMAB
rQUDAmgrGFBCPkDbhDhOaFQqyPjrV8qzfrSjZ7Druu5SGSfem7gxyCngO4o+7sF/W2gbL/uI/MqgfGYb
KWMtg11d10nhFkjflytXlw85UaZI6MSjvqsiweBb+YKIruaC6Kw638/4r6mTtx93/FNihj/KSilAUa4x
467X6WRHI4SVgNToYqb40diNwVf5gx9O6Dt3YX+QXnDH92/SyZnvA3chC9IbdWGCOUsGlELbJOG0N33N
a0AbA1pfNyU0xe/05vAltN3JWNHgBD+SqJ50fC7eM2ThJho3PBep/unBQ9ukJ9v+DAAA//9SPclr2gIA
AA==
`,
	},

	"/index.html": {
		local:   "../assets.min/index.html",
		size:    3443,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/7RXTW/cOA++v79CdQ5pgVd2mjTtNmsb6GWBBXpYYLHngiPRNhNZcvXhTNHOf1/I35m0
SYpmL7bFj4d8KJLJ5C+kEf5Lh6zxrSrz+GQKdF2gZrrm0HUFdF2Zt+iBiQasQ18EX/HfJlnjfcfxc6C+
2PMAXJi2A087hUwY7VH7IiEsUNaYTC4aWix6wtvOWL9a3ZL0TSGxJ4F8OPyfNHkCxZ0AhcXrOwASnbDU
eTJ6xtiqIfjG2FXjySssHYgbQXk2nvIdOGSNxarIylyRvmEWVeH8F4WuQfSjLlJ0V1nWwl5Ine6M8c5b
6OJBmDZbBNlFepG+y4RzqyxtSafCuV/Ar4z2HG7RmRazN+m79GwIsRX/RBQh9bVLhTJBVgosDiHgGvaZ
op3LQNdBgeXKgCRd8x3Y7Cx9n55lG8kTwg0ZKvBPMBtkT7DrqENFejIdb585K36SWnrtstfp2/RyEUQ2
167MsxHzObG5NcHjfxsBnQlWPEsQXf+pqzh1+LewRqnsdXqRnmW65jTJuRsUz8iIB+LrCJ2nl+lZthVx
3yn3nPEeb+1fDKTQuXhP5+m79Hw+fR/x2mXQdXfVGnomFDhXJBr6HVg2vjjpHq3D+VjRHiX3pkviqo6b
Lt4M2kJDTzXEzVjmkmawaACk0fJKBZJb1QTYIEi0ZQ53xTsLWo5jeLJsUCjzTFI/opCcbOe8hVEKujXV
+ZyUeVAbcrNeQ5/E6R+IjNqvIDz1eMXIfRi+Xp5mp68OSUxvWtl/WXONwrshm0edoUbt3V2IUVZ+GF5P
hJEt6SOUKCo/xCfFlo2VHysU1I8Jz5+W6sYv7F1jbgtFPf7TSfDolignbNiJhTDK2KuTi/cAl29/F8E6
Y68kVhCUL3OaY1XAKuCOag0qKfOMyo/UIxtRJ6Yrdpm7DvTsW6svXUPCaLZ8cWXiDohI0bL8aGoT/Epy
7IXpqaHfdldy1HmsIhVz2lhYc/sdqTCKt5Kfs268aEXOH/f6RlXmlbHt5FyR8rGXVzjSXfC8tiZ0d+hu
5BykjENzXEUEK5qxihP/fPCaYxnbzjmxToHAxiiJtkjGLOb83ZB8a2T8AzdgpvF/laVuEafMmztZT6tp
bY3xfGwSqY4ozZvy4+QzzQf7A1GmaZpnzZvZKqg4tHNeC/qLBX7sRosdgi+SyZCRXriwb2xkd7WUp7lc
Z2cyS50HH9y9kooGxc1QDqoW+MmYFQU77cA5lKdT0Y+8Lbamx4fcKyD1Q3fciwZ0/SCADVqTrn+A8Dmg
i1P+EMItkN8gjG0zr4zJPvv6dfYkeTiU6zE2xuEwDtjg+r9HfLNdICU3wuH8SYf2cDjOclGxkp0l5cuT
73q9GqM3l8PNTvw97j1vg0fJJHog5ZL7lwsKtQS7YR4z2JGWaw64RxFiDT95apF9Y/EFtUnWETtCVUbc
cHOv5DKMG3fk8kDExfAbmz8fBRszGWqw2XP3d9T7+ZcGjz9sBtj4cbQY4/PfAAAA//9YKgw3cw0AAA==
`,
	},

	"/js/app.js": {
		local:   "../assets.min/js/app.js",
		size:    11696,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/8w6+3PbNpO/+6+QObmAjGiKzsNtScOJ67jX3NeknTy+b3KupgOREIWaBFQAlOKT9b/f
4MGnKMXX9ma+GQ9FYJ9YLHYXS68QH6HlEiKalTniQcHSMscuQMsl8G8cmr1npcSOr96wYCVP1KAkwYwx
KSRHS8d3CJ0TSiQ+EQlnee74jmV3kjOUEpqdzBB3pl6MlssgYXROMnde0kQSRt1HXEn4hbMVSTH3H+Us
QQpQzXibLkawXmDqOhPH30hcLHMk8SeeR86Ss99xIoOFLHJn61VoKC0I7ePqyT6mZTCJSPpA3i2KSSTR
7E+STaJZSfKvCY13LKMhL96yFLuSl9iLt7WFpdoHzF2HohXJNJXjNyYXCVvixtTexswERFwmkqwwrFFX
BK9/qtE4liWno5owWCK5cL1ASMSl+BeRiy5BvB3SyS4sJ0IeUMq3aMKfY5zWKlqPgmrFsZ2rMGH1EvxR
Yn7X+NgO9RzlAseKccBxRoRUel2v5C9kiXNC8fc4U15jdar54JX0NtVRmTN+jZKF21OiwbYz3obMq/eA
pBBCvJIV+m8k9Y42FVRIJEuh4eY1riD4C05KxfU3SQqsMdRLDdce9BstCw2qRzU8Lbm2Kgzj7VZ7yv7F
/0AoEQuc/jutv9ZfwapBTOZugwshdNaISEIzp8WzsUy4z5rKJsYo28FDZMkOOauNUYijQjSeKznJMh3C
jI0kmsE2pppQi2iBISxpiueE4tQ7as07CyIk43eOxm/z0CZtEZlDWp0NvfyuUD0Vt04ETu2B6G5lc5wy
LN0NSaOe3K0/fMJwao6nClp2BcYQcBffQj6YLaw3sEd4zTnj0HFila84FktGBYYW+DD1ujGricLOuEc2
dibaQhNnXEmyTkRSL24xxUqpfQvRwOFlaFCQIom0v/Vwvs/LB9hpr4EORdzvTZrZ8eK27+qVmpjr5yxr
5JMCC4mKJQwr0XodVyzF8Hn4vDMJHcrkaM5KmtaKCpzjRH6QKGulF0JT/MXbqF0VGtL22kBPiRuNNFV+
b3Ba3n5/r6daEYBklHGcOv1zYEj1M85ZZnzG2qXvOL7ypbYitCx8TRppXVo+oDyktpHRJWcZVNPqJRDL
nEjX+ZU6JrhoBxZlkmAhYIeL8jN/gVGKuRiwuoW43o3z5aSedqa7mxH2tsIcGmN+nJoNCOMBQ9cRvdZL
z+v43TbzccfMHcbj8dbTG9WevAjrSNZygi7OyWllHKP1nkOG+wdoZ/UGZrPH1sYLk+R+wCrQNbkMU+kn
KM9nKLn1Nt18aKCD+Y/MXbe/PRdVQtYj7/6+G0kDkh73016NU7uYRakTlndkC654e0TmrrxbYjYfVRor
Z68Uc7yjalrr2LiaZvZmMAGQuVtBO/mjmnRUJSqk080kJj589fhYJlvf+rpv9jFu74UuOq5YURD5gw4V
PUN37JNoPG0g86rWuMNtt4Q5wHK32uiAh0uOIanag23JeFieCmdWXoan+zXYHwwb6sMGGDJoTbvvqL9D
BR5UOliWYuFuKCpwVGP6RueoDgZ+ZaUoVLkjupnWJdWwzX5iWV/HOhW8SWGtb6tG6hjDIk6Ph6qmQUwd
lPViFPMCC6Ei3H4NjSP9Pyg56Bq1ll9xzT76Hlc9WM3+aOvJw+WArTrtHUyt25K/SeEScYHfUNkvRz0d
eXKizutpaLLPLWkVDqZN8H0p7jrXODN9TXvVKMVf5C+dqqFJuD1GSswYaslN9BPQLsLeCgcqRV+TRPrp
KyaRenTqxypaiiDHNJMLCGErrdWat9djpXdGaicSJC0vb8AiZu3twvBvXMU+cT3XrRZ5rnntW+beUngn
Sx+8bh66a9sLXpM1jyGsHbAu8dRW62LTrmbPDbUqbSsJetzsrErBcDcFG8Z6wfvShpnvXswtS12SrGSA
Mkxl3Ess5i5O5u6xFtILCiIoqViQuXQ3tCyijl5V6G2U8JWoqBblKyWiSptWYN56279y+X/Yhlis5uqt
D0t3dfBmGtflzd+6Y4e36WCs3LVLpz75Cyb5O1d4oCI6GPKv6epwuG8CxIKtrxidE140YVdN1hiJharJ
4UunwFJd5cUDM0zVbKglrAhe/wPf9VoTJW9nAj3pbeqiqdtDqCImxwVb4a+2CLpcbOHqxN3L1G7Q65LZ
e//+QFiH9RTnWO6upYZzrMot2M1BlfUXiJoirF1VPH48BHYc76ju5Ai0zxCmuNthsG01cecoUfZ0QcUO
tLaW288DTZe4mnGdCVqSyeq002L3drias/BAnmCHZ/VimjcRSYFf31DAK/sG1OUEvCIp2O4qYP3lT2tA
0oll8dJUPyYXP9bVj07GwN+YJA1e6V9g8jR4ZYAHdLN9nr+iW8Vil3nOsr/P7JOcZRNzSzi8A7alAl4Z
3K2/ybCMNgWWC5ZGzn9ef3R8yREVc8aL97ZFEtVqqgNVabhR1w01sd1uB4ynwnpngYzJD+a4Ne9BTlb4
0zJVt16T73XlKjCkeD26XmEqP/SMoPl6sRA4YLTXuOiwfoSWy/zO3SNMRzh1zgwjeyv5U6zshyCbWTdV
Kou6bQ9ze9OxuGmA6CqKwt4FdkdwS6uKNjAQIbB/818ffn4X6JuBzop6k6a2IaGWh9JUm/InpRetOi1a
oTn1bNx8xKgLHqVYSM7ax9HbKBYmnB/ioqQ1UYvkOpmrQghlzGmzs/5dz+hiKWcJyn2O1jriHqu5+3td
3UHohGF4eqL/PoZhpP/+u242jhyKV5jrHv2xZuNtXP0LXyOJA8rWrufpbk5VDxChIFqw5220FPUIMiw/
kgK7XrzFucCjpgFUaSIk1586DJHy0YZTm3xAmlHN2xjV9POAQIPVlmhmapGGXV9mS91jCAEtixnm4P6+
zbUF8Jpm1wrxIzafCyzhWyQXAZoJ1wjRnU9vchqGoeeLJaLwZuq/ffPu08dreBb6P/786T18dhaG/uvL
z/Dbs+dh6P/r+vof8Cx8/m0Y+m9/fvfxR/j07Ol33zx/7n++vnwPn52+eHH23dMz//X11eXr63ocqj00
SpzDU1W9GnEA+M7vpZAjytbONOZobS9DR5XVKiKjlleTcbR+CShbgwigUUFoKTGYxj0q11A9OQs9S6kt
wFX96dbGMMgTK8HzQUHoAC9ljidPnz+Ak8JUfBZ8gM3ry89PvnkAk9eXnxWPFN0NMFHb8OTF0wewUZiK
zxrj2wFGateenD7EPApTMbrDaHBZesOfnIYP4WWQ9fJwgtJ65+rdBWiUM5ppdwfTWM3fnE7H0NVv4VRd
ge7v7eDi1HsJBIgA0IhQPYLfGaEuGAF9I1R+BU00r4KUQoq3NtLoY35ujq73UoHGYIQyBiJA6AiMDbKN
gCnhWH/Xd0GClkSinPwPBrtxcMPxHyXhOAI0e8tSnAM/J/Q26paoPs5xoa6YSEou/EIhXkmemwzSCGh/
5VmW8p8oL823hGbYbTy35gGIu8xS2EADyT4tl5hfIaGCDZm7LbxjCNviau2CRwLLfxK81oA2hRe3kDim
KeY6hFmztzDjbRtVJzluW6MNlhc378ZgN9pQgbXpdCg3ISpIwnLGHf8GPBJJe3fU0GZnxnGm/fNK4Qq4
AeEpiMCM5SnwwbNQvecouVUDBeBYzz8FEcg4xlQNnoEI3OE8Z2s1eq5JSqzeX4AIFLp7gNTwDEQguUOa
6BsQgfWCSAyq0qLJmSuUe0dqX1c6S7Q2VE0AEP88099AbvGdcPtL8HY70coWtsWqzgY4Vz+jJEdCQG2o
ERj32dyo+ekYOBfGcZRFPuyhVrCvssjhCuUBx8scJdhVme49zq6/LF3wa/js2a+/3oCxwh+DAvggAyYZ
eYcIwvj/THK6Q1Kt67CkA3TK8fqrm2i6m9NikvngfHYBvD7o6VMDmyjgPvpnBocM0VvYhBygtyjKKgew
wgeixQ9EfPZdD6+68ogEB5KXQl6KH2WRazdXV+Fp5+SCqoM0EE5H3QDobfSPCU+6hAnC7o92XVMZiKa7
bvDPQv809Oyn3ITRVJjaKMEkNyj/cWbhHIsyl9DRZahldxGqGlXNj6GdGjsFoSPHfK7VHNtIdmrsCJw4
lVEMsM4rlQ24KnrFUEZpmUDiQtTTehSInCTYVd6i6d12q8GyLuktZWsK9oXFvhghefV55i7H1gZCclW+
Wl6Od6SBY+jMGZUnehCNdMhOYmevA9hQYhmDsWGi4sVYSD5uudCul4gF4/KgfbTita47/84zcmrFhOSB
KGdCcjf0v/F2dmOG0gx/4vlBcQP/m/UVsWtCU7YO6n+jYZxkhI53ejvOuPnoPXYmWhtnoBRxbAex3R5M
WLEkeb2tprUWbSxmBB6D7dcrEm9j8q1K+C6g2UmSE50SW01NZMwCvLiHq3CAD471rxdbxurWeqVSiAus
Li2YuY5eSsmbNZmDmDAqMZUfef3vtZZG+ZLkqly0IqGjns7Fh5Ljl+cTA7x4TGdiGYPxETiflVIyOlJ3
J+iYgVNltZmko5mkJymeozKXTo/pqDIBdO6wcD3lsEfgnFTkczSao5NkgZNb50KF6NFnLM4nRsif1sEe
kwLxjNATTrKFjEbfLr8c0I6yfcoZE1vt3rFaufYOzZXzVx7k1qb3bF/Vi2uYJakg8U7L23wf2O0MK63N
d0bz3x9YSFXfbO34DotdIusR7oC06lOfnaJsj0iLpjtb/xsAAP//UR/MSbAtAAA=
`,
	},

	"/project.html": {
		local:   "../assets.min/project.html",
		size:    2141,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/5yVUW+jOBDH3/spfD6ptA8U3WsP+6RKPe2+rbYfYGVgQmbXGSNjaKOU774yNiRNaZLt
S2Jm/vzMjMczeYU9K7VqW9FY8xNKl/YIz4zqtDTkrNEa7OTy1nZtnoU2qoJK5ut/ZF7I3S7670htYBjy
rJBXOUYsXym2UqmiWkNama7QkFqs147LPEOZt40iD8aV4E4VTAiWFB3qKuHywf/nmZfIq0XlGltn7HbS
si/h+eQ7DTagkSDh8ltcntQD9QmXj9SjNbQBcifVLTiHVLcJl09xuagfY2R/CdZRBSskqNj1NZutiVYO
WpdwefP3bjeah+E2kvLMZ77TU4pJ9YxUnzpVtFzmGsfzC76dKh32cM/eJnfgMldetrawElk8wWx/llgN
QzZqs3n/kOT7Twayj+NEQsQh5/WVzdY9JyzmVKhzAU81EkI+GW+UHhfT2S3mkrpgj0l7UHxn+b4EL0AD
9W/r9Cx4rtYL6JP2oK4DP/aPTutws2VedM4ZYm7bgIjr+AWFI1Y4ShuLG2W3/ODjnMW6BvvklOvaELa1
xibsP5b4VypFNdiE3YfHSEgiAstfIhJubr2p0J2dLA+689bGNKYHmzp0GgT/Sg4sKc2ewPZg2aPfjrMO
izQqxW4XCaNvGGZEo1UJPslCw8rtyUEteELGd5jZgW1qGqCPo+TH/eRY9+ZavKckXB733Earbeiy11S0
zb/fO1puXe9gzwr9CS8wS1P7v7ZBCujLoVOcx0h4KbXaKIeGfP7GSRHY/yvUUM03PVSSzLNOy4PB5Vvv
OK2AHCs1KLvCF/5O0SgCFuqffzBwRjOVuqtA8CQW/4/Rebd2G+0/Pquw/yP2PKKW6dH9ef44npbZQP3n
uftBtgyf/Ec7HPz+DgAA//9y1EfgXQgAAA==
`,
	},

	"/project_build.html": {
		local:   "../assets.min/project_build.html",
		size:    3573,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/6xW33PbNgx+z1+BuLu6vVW2s6S7mytp13W79WHtdmnfe5QISZwpUiOhJJrj/31H/bJk
OW4u3Yss0fyAjwA+gD4XNxBLZm0QlUJyjyMxIS2o1Iu1IqOlRBMURv+NMf3itoQDzIxJNAT10+NMpWhm
DiqSYIbGaAPnAZSKYyIUcnj+HPrV+bz/fKc5uqWr1dUs9C0ZrdLwt+vrP6/X/rL9hO223rvb+UsuboYk
jL4FS5XEIGcmFcojXawvVqvibkSl9hJ0XgZniLX0cu5dQfuik8QieVez1irhHXlMilStY1SEJvRFh00Y
JMyLdZIgdvsTrciz4l+sSVDoL0XoZ5fhRw11jC2QBot4Dp/ZBoFBXBagE2isgDaQsypCICPSFA2wBgY5
UyWTsvrZX2aXYRuGfTBGYQ+GYb+/h351Ph8fvmAKJdRPj2PCSkmjDc0/keZVXRL7SllYYlTa9swF41yo
tA796k33FWkina8vVsVdvyYxofXlqrg7SOHws03Ej6Gfve6X8lzQNPIZxpu+5EbE3GELZi1yd2SXgwOs
wVzf4MPghAn5IBjv4szV+8NwUyolVNrhbcGU2xsJxb2MctlBmpMtcrSWpQj3UKqN0rfK4RwofK4iW7x5
8Wy7bQCqzHe7l/4yez2IT12keUnIJ1RLi8bTAxqhH4VvS8q0WfvLKISvcmP15iPU+p/HcomFiSV62lOa
4uyA07vaW83pzGeQGUyC2XbbNp+WzJfSyIXBQrIYX8y3BpPd/BWM6BpMXu52fWam+Kb/zICYSZGCL5Fk
ahP2Ad6bgXuwmTbkug4Lz/pAHTe7kKhSyjqZfcXeNICHja2VweUxjT0y3Eyi4swcBPqzyPFI6rusk8hd
HXJGuJ5XVVV5Hz54nMP79+s8nz89+ZkuTeoWvIzJ5IDTr6VhJLQ6wYu3Wxy39vXpZCyaGzwMzEfN28D0
YtMcB9nap2n6HHRVN5IKUaAUCmdHUvrTE3pwhsylP/yrtQuf6l4zcT7o2E3d6Bs0idS360xwjmo0Lfqu
laKdDI3hn4PaXs1chN04644ILegVxAYZIWiFIBRQhtAJ+dn5slXMci9pwXe7ZWelP5nTGhCLFsdl0bJt
TnCE42Sv22qwQEbBrFkQanS4Wbjd1m8LxXLsrxiHjiWr0DzWLxb7gdnYbmfDV8k0OBFvAosSY/rkll98
JxTHu5eTOv6nRFsroUvpyJlrRSJV2jx2Ck7QJ6fgePxOsCfHb6zTWoeFOMH9YIg+JL2HOuc3yOxt7KJ6
Sl6hH5VEWgFVBQbte+srIgURqc5P/R5JHW9mRxKQGLTtLIRrNKWC+qLtLxub4dn/44jrWyU1462n35Hg
rSGRsJhs7+sRwT1+Wbv44RuC/YdO13BUg4cmm8YmdTqyhnlBVVtE540VqdNOlx+1A4AuqSgJYlZQaZBD
og00CkMOTrCLqeJdcxsI1pkRCnoPQIbFG4gqaOTZF/LeO4R1w6zn2d6oMuF222Dge7joJ8zZcGN3JRzf
zJzbe2DKilhLbQYT8KQ4Bs//AgAA///xPLrG9Q0AAA==
`,
	},

	"/project_env.html": {
		local:   "../assets.min/project_env.html",
		size:    1068,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/7ySz27bSAzG734Krs8rG9izpMUC2wK95NI/QI7UDG2xHpECh1KgBnn3YiQnNdoE6KkX
gUMOv+9HaurIM8i5CipumhJZM5p+peDvZG7vdYKAAlMmIJnZVAYShxmNsUuUwRVGNBzIjb8RLDoZdBOn
eIBPPWW6uYpGgHBWjTAmDFR6s6sRjJjzg1rMf+96zS44UAY1sEmcB4JM7iznDB0FLCze07LqifqmEYEF
UBYYpy5xAJyRU/EFo1Ezu9qyIm19OI6JKe5YgDD0GzKUJSALGWCGvGSn4fWxD/B+Mu/JhoK/3GwpYEqv
9+we2HuWwg4ZwyUwfP5wqH2FDAlzbvbbYf1Wvc5k+7b2njC2tVsJ2y9XObjDgbZEmtbgv+CskmvvNC7l
fvmtRiOhN3uSuSyIZM77kmdhb/ZB5cQ2QAMnTJmKWWwfH0nmw4WWp6cfx7m4rIkratBUDbH6p627yV0F
fBmpucbXaToX6FyqiHImW31D4nC5NXabaK3kXh+av66FtuZnkRPCCSs3zH2leyjjVz3HSNKU3rY+cgv/
UyKn+rj5t7s6u6mcX3SfZT9ORv/Wx63a7n6HnU44JX8dftvaLy4/w4eewuUt9HvKN9x/Bsho0JneIrrT
F6D6uL7Ftj5GntvvAQAA//8sG+2nLAQAAA==
`,
	},

	"/project_history.html": {
		local:   "../assets.min/project_history.html",
		size:    1981,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/5yVzXLcNgzHXwXezNjJgat1nfSwkdTpR2Z8aNKOJy8AiZDEmgI1JGSvut537+jL9srr
Ns2FQ1IA8cMfoBhrcwdcqtyxeGct+aTx7i/K5doEcb5LB4vcYgjJCi15gWFUGrkkv+qdQ+XukxV57zyc
JdCypsIwaTg/h8fdi4tVGgfxjsv0083NHzfbOJqWsN8PZodDHGlz9zykd/cQpLOU1OhLw0pcs73cbJrd
U+CzkPfov7Sh6yOeZa2xOqwtcSnV6iiB3FlVa/UepokrikCi3q+mIEI7UWhNyducWMinsZl9C4QCVe6K
gmi2LxyLCuZvGpgkjSOTxtVV+sXBSAHiIBCdwVe8JUDI2wZcAeMp4DzU2GUE4k1Zkgcc3aBGbtHa7qc4
qq7SSZUnbQwXho2QGjNPmHbyJ5b09t3yk9ImCHJOyebUJ8ws6WT1TMCHBxhXn1gfa9cgk4VhVJoKbK0M
1ffUEEqyGskNT5kfOY9emdPd0GzD3mC2DoLShknOBrU2XA5F3nycV5kTcfX2ctPsHvcsFbK92jS7RbM8
X041/jGNqw+PW3Vt5GVRK8pvh2RMMSUygyUJXDQYAum+f/vyLnw91e6OXncu0NhXnWmXV/09et3dt8yG
y9k/NMhpjFB5KpJouqrRfj/N1kYfDtFwSLTfj4dxWx8Oo2cfJTOsVSW1nYONmqxrCgFLggdo+ZbdPfcR
h3DnnIXm49s3Rwe+iyOcDeKo+vBM5OES1a2QfpFvG8grd5RLlv7cSuX8No6yFP4TEwfjE5T/myU3Prek
nGInebVg+nWINjK9OYJa8Hgq4AFC5bycRln+0aauvDrV8t8IjpZYo18gfzU1nRBx5hVT98XVKLS96Lqu
U58/K63h+npb1xffL2PlWl/2G6pCWyyYfms9inH8L1x6MunZpun3wwTyd7QU5ovTkzCPHew09Y/NizK9
HI+fovnNefphLkqr+9pe/vDNz0loDDP5eTqS/+6w7wmonSdYr9evwf0TAAD//yCRZ/q9BwAA
`,
	},

	"/project_settings.html": {
		local:   "../assets.min/project_settings.html",
		size:    5417,
		modtime: 1504367759,
		compressed: `
H4sIAAAAAAAA/+xY62/cuBH/vsD9D9MtUN8Bkfbiuy91JRXxxbgEuQSGnaS4fikocSSxpkiBpHajOv7f
iyGllfbhdVsDBYpegKx3NQ/O4zcPKuFiDaqKCq2c0VKiSS06J1Rls6Q+B+t6iWnDTCVU5HR78X12bfTf
sXDJqj7PvHghmbXpsmUKJfjPiGPJOumWhwxRrnkPuf6yQzN6M/9ZaBk1PHp5niXWGa2q8VD4wBpMVsPD
JDfZxxpBsQZBl+BqhHZgFBY6ixyYBQZc2Fay3jPG8KvugBkElksEp8GgVzCXZg6Y6sGJBmM6xf9fcbEe
P2duGb0BpaPaLI+48OP8mVBt56LK6K7NEv9jIJTaNGMKKBuN5ijTomaqQvKYnq2Z7DAdDIzJ4myR2Jap
Q+VR7lSW5J1zeqQuc6cgd2qbGXB9i+nAQwCQorhLQyi+/S678V+SVWDIkhWdtBuC/UA8mcPLTkgOH42o
KjQ7Sbx1zBDmgEHumQqmIEdwgRc55D2smRG6s2B1Zwq0MVxrKUmIEnf703sw2GornDY9lNpACJ8lJBBH
o60LkNiwPl68Z6pjUvbjGaMif76F0ujG/95gDkI5NCUrkHS12lpByDmKkcl/bnTL9eapRMDIFzldVRJ3
E8OZYwNhUhhMHwO5A4KCGXRTtsbsdXLPqKhB1WWJFFnCoDZYpr/fU5us2B6dQjyE/JD4F8xrre88YdXJ
ZyKFjrrZZnMHKlesqOdFLoW6Q05lzBQsbz024CfNEd4zxSpsULklGLSjthjeOqBaY0IFZARAQSkkWtjU
oqgX1B48VpweEEmMBNKSFc7GcIlWcDwi77uIaFEKhcCxFEo4oZU3VRfMIV8INRebUBvDtURmkawrRdVR
i5ISFBZoLTM96JZUWY9ur6Fo5uLPbVTUheYU35WGbiVZjpIOTunAqDMymxIEn25+SVaeJVs83tgE3wof
NrTJj0PLTxiSG6aKOrv0fyYbLErCxwkjBsFFEoKa3d+PlgTKw0OyClq28QzxOQR2+KzPqY25zsIl4xX+
d8fjlfLDzAYD8mDAQIMhI76vFDUWd7n+Mk2ZrdsktB2pc02EXQa2ITDefv4ZRMMqj1uDFpUbO6dkDq0b
ymWQ1yX0ujNjwcZAuoPSocWvBW6oJwtX684B61xNOgtGWYn/41Hjj/CwnPUOGvx0bGfDtC+1lHpD9n+6
+YVKXahCdjwQdyOgnA6ebDC3ws06fmv8eM6F4ulybExfg9wnI5dZsmoNnsTNaxpUBv6q1b8EG+Ce/5no
+eO0W3WmQgjT+Y2wBy33Y00AKHwbM9joNVrfmIZR2SknJCi9mYYmja2cWYzhlbW6ENT2pu7ply+OEl3Y
zzYoZXyQ48HMH+bP2k7KyIiqdtupurfGULtNl0PuUjgTXOLZcj577+9H6kiGP8OZn8g+rGdwAWdnDw/L
sBV5uXtPt11BnfjsAmYaxocvgo4NM0qoapdnwwRVydnDMrR206QtxZya5WhayaBkUc6UP9fWejO5sfUj
S1Yi25cpdEV/bCsekR2Pf0ScOsJxwdG344L4pZCs8XUaOSOY8tvLMT1ojDaDlj+o3LZ/GpaWU9bC169w
GICA1QmltOecUDaefH/vv/mm/oTI5PRt+HawTf37q81Ua6897GF7h5qVmSeFJXhsIwZtJ50FMRSep0o5
ldKLsQiZ4tu1wafksBhhtc8hJP6/1V1oO4eF5wyzdaR/K75TxXcA3v+16rs2Ys0cwjvs9xcD2lEC8Q77
7dsDulZMGwkCq+jW4Ob7e0F3jdnVUxvQrkYDt7dvgOqOg0WzFnRlXbz1dxZqXsipqkMgwkuWUisX+a8X
wjEpimzlmnYl+N+MZUMYwNUsnD7uAnRK54QUTqCFUigOwoGvVWB00927FTyr0PevsGFvCW+HltNbhCUt
de+whxR+N3ydYXPcBe+wjyWqytWQwffLw5rEHo/DVpTpqDf7LHAz5HMXWqJMR543guOMZ4ulxXN8ZJwH
F53p8LR7SXrUv1Z2du6gNz17xfkxW0/i/vTV7uWwUT6ZgXGX9Vxj8KaL0R32VMJ+m51zbnMR0b/Lq5/f
foCb21dwffP286uPV/Du6ldP+Waxoyu2XW6d+faH8xfw8vy7h4c4jr9ZeM6rD6+PathZpR1+ccwge+Qd
mjdtSJLRG5ue/zgUmkEr/oEXSivSNap5fEP3n/8MAAD///g/psgpFQAA
`,
	},

	"/": {
		isDir: true,
		local: "../assets.min",
	},

	"/css": {
		isDir: true,
		local: "../assets.min/css",
	},

	"/img": {
		isDir: true,
		local: "../assets.min/img",
	},

	"/js": {
		isDir: true,
		local: "../assets.min/js",
	},
}
